print("File: homework2.py")

print("Questions (Answer these in the homework2.py file as comments):")

print("1) What's the difference between Git, GitHub, and Git Bash?")
print("Git = a version contorl system that tracks changes in your work over time. It works locally on your computyers and lets you commit/undo changes")
print("GitHub = website that hosts Git repositories online, letting you store, share, and collaborate on projects")
print("Git Bash = command-line terminal for Window users that lets you type commands to use Git and work like you would on a mac computer terminal")
print("2) What’s the difference between the terminal and the command line?")
print("Command line = interface where you type out commands and see the output of them")
print("Terminal = the program that hosts the command line")
print("3) How does Windows PowerShell differ from Git Bash?")
print("Windows PowerShell = A program that takes what you type and tells the computer what to do (shell) tool for Windows users used for Windows-specific automations and commands")
print("Git Bash = A shell for Windows users that lets you use Linux-style commands and Git tools")
print("4) What’s the difference between Anaconda, conda, and Python?")
print("Anaconda = software distribtuion, includes Python and conda and other preinstalled data libraries.") 
print("Conda = installs Python versions and libraries, keeping them organized. It's the tool that manages Python and its packages")
print("Python = the coding lamguage itself, what you write code in")
print("5) What is VS Code?")
print("VS Code (Visual Studio Code) = a code editor that lets you write, edit, and run code in. It has mulitple programming languages and offers features like syntax highlighting, debugging, and Git support") 
print("6) What is a Jupyter Notebook? How is it different from Jupyter Lab?")
print("Jupyter Notebook = a single notebook interface for writing and running code")
print("Jupyter Lab = a more advanced interface where you can open multiple notebooks, files, and terminals at once to work with") 
print("7) What does ~/ mean?")
print("~/ = home directory, a shortcut that can be used in commands to take you to your home directory")
print("8) What’s the difference between an absolute path and a relative path?")
print("Absolute path = exact location of the file/folder from the root directory") 
print("Relative path = location of file/folder from current directory")
print("9) Imagine you're in your 'yourname' repo. Write the absolute and relative paths to 'course_assignments/homework2'.")
print("Absolute path = /Users/maihaller/python_decal_sp26/mai/course_assignments/homework2")
print("Relative path = course_assignments/homework2")
print("10) What command lets you move from 'course_assignments/homework2/' to 'course_assignments/'?")
print("cd .. is the command that lets you move back a folder")
print("11) What would rm ./ do in your current directory? (Don’t try it!)")
print("rm ./ = deletes everything the directory you are in (usually will fail though because rm is desigend to remove files, not directories, and will cause an error because ./ indicates a directory)")
print("12) What do the following commands do?")
print("git add = used to place changes from working directory into staging/rough draft area")
print("git commit = records the staged snapshots permanently into your local repoistory's history") 
print("git push = used to uplaid or transfer committed changes from local to remote repository") 
print("overall = allow you to save your work")
print("13) What's the difference between 'git add .' and 'git add <file>'?")
print("git add . = stages all changes in the current directory")
print("git add <file> = stages only the specified file") 
print("14) What do 'git status' and 'git log -1' do?")
print("git status = shows you the current state of your repository, which includes which files were/are modified, staged, or untracked")
print("git log -1 = displays the most recent commit in the repository's history") 
print("15) What’s the difference between cloning a repository and pulling from it?")
print("cloning = makes a opcy of a repository on your computer") 
print("pulling = downloads and merges the latest changes from repository (updates an already-cloned reposiotry with new changed)")
print("16) What has been your most frustrating bug or error in this class so far? How did you troubleshoot or fix it?")
print("The most frustrating error I have had in class so far is with a demo done in class 5 where we had to run a function from VS on our terminal. It just wouldn't work for me and it would say") 
print("that no such function exists. In the end I googled a bit more how to run something like that and I ended up finding my answers. I learned that to run a function in my terminal") 
print("I first need to turn it into a file so that I can run it in my terminal int he first place")   
print("17) What’s a question you still have? What’s something you’re confused about?")
print("I feel like I'm not learning these concepts as fast as maybe other people in my class, is this an issue with how I'm learning/studying or just me not practicing enough? I try to use as little ChatGPT and Google as possible") 
print("18) Tell me a fun fact!")
print("I have 8 siblings in a freezer (I'm an IVF baby)")
print("19) Print your favorite math expression you've learned in Python so far.")
print("(Hint: Use print() and add a comment explaining what it does.)")
print(42 + 41 // 42)
print("42 is the answer to life, the universe, and everything! My favorite number")